# Site settings
title: Antonio David
header-img: img/banners/home-bg.png
email: antonio.david.us@gmail.com
copyright_name: Antonio David
description: > # this means to ignore newlines until "baseurl:"
  Musings From My Journey With Ruby
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: adavid128
github_username:  agdavid
learn_profile: agdavid
instagram_username: adavid128
email_username: antonio.david.us@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
