# Site settings
title: Antonio David
header-img: img/home-bg.png
email: antonio.g.david@gmail.com
copyright_name: agdavid
description: > # this means to ignore newlines until "baseurl:"
  Musings From My Journey With Ruby
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  agdavid
learn_profile: agdavid
email_username: antonio.g.david@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
